import { db } from "@/lib/db";
import { tests, questions, options, resultTypes } from "@/lib/db/schema";

type TestData = {
  test: {
    id: string;
    slug: string;
    title: string;
    description: string;
  };
  questions: { id: string; order: number; content: string }[];
  options: { questionId: string; content: string; scores: Record<string, number> }[];
  results: { id: string; type: string; title: string; description: string }[];
};

const allTests: TestData[] = [
  {
    test: {
      id: "animal-test-001",
      slug: "animal-personality",
      title: "나와 닮은 동물 테스트",
      description: "6가지 질문으로 알아보는 나의 동물 유형! 당신은 어떤 동물과 닮았을까요?",
    },
    questions: [
      { id: "animal-q1", order: 1, content: "친구들과 약속이 있을 때 당신은?" },
      { id: "animal-q2", order: 2, content: "스트레스를 받으면 주로?" },
      { id: "animal-q3", order: 3, content: "새로운 사람을 만났을 때?" },
      { id: "animal-q4", order: 4, content: "주말에 가장 하고 싶은 것은?" },
      { id: "animal-q5", order: 5, content: "일을 할 때 나의 스타일은?" },
      { id: "animal-q6", order: 6, content: "갈등 상황에서 나는?" },
    ],
    options: [
      { questionId: "animal-q1", content: "약속 시간보다 일찍 도착한다", scores: { dog: 2, cat: 0, bear: 1, fox: 1 } },
      { questionId: "animal-q1", content: "딱 맞춰서 도착한다", scores: { dog: 1, cat: 1, bear: 1, fox: 2 } },
      { questionId: "animal-q1", content: "조금 늦는 편이다", scores: { dog: 0, cat: 2, bear: 2, fox: 0 } },
      { questionId: "animal-q2", content: "친구에게 털어놓는다", scores: { dog: 2, cat: 0, bear: 1, fox: 1 } },
      { questionId: "animal-q2", content: "혼자 조용히 쉰다", scores: { dog: 0, cat: 2, bear: 2, fox: 0 } },
      { questionId: "animal-q2", content: "운동이나 활동으로 푼다", scores: { dog: 1, cat: 0, bear: 0, fox: 2 } },
      { questionId: "animal-q3", content: "먼저 다가가서 말을 건다", scores: { dog: 2, cat: 0, bear: 0, fox: 2 } },
      { questionId: "animal-q3", content: "상대방이 먼저 말 걸기를 기다린다", scores: { dog: 0, cat: 2, bear: 1, fox: 0 } },
      { questionId: "animal-q3", content: "상황에 따라 다르다", scores: { dog: 1, cat: 1, bear: 2, fox: 1 } },
      { questionId: "animal-q4", content: "친구들과 만나서 놀기", scores: { dog: 2, cat: 0, bear: 0, fox: 2 } },
      { questionId: "animal-q4", content: "집에서 영화 보며 휴식", scores: { dog: 0, cat: 2, bear: 2, fox: 0 } },
      { questionId: "animal-q4", content: "새로운 곳 탐험하기", scores: { dog: 1, cat: 0, bear: 0, fox: 2 } },
      { questionId: "animal-q5", content: "계획을 세우고 체계적으로", scores: { dog: 1, cat: 1, bear: 0, fox: 2 } },
      { questionId: "animal-q5", content: "즉흥적으로 그때그때", scores: { dog: 1, cat: 2, bear: 2, fox: 0 } },
      { questionId: "animal-q5", content: "팀원들과 협력하며", scores: { dog: 2, cat: 0, bear: 1, fox: 1 } },
      { questionId: "animal-q6", content: "적극적으로 해결하려 한다", scores: { dog: 2, cat: 0, bear: 0, fox: 2 } },
      { questionId: "animal-q6", content: "피하거나 시간을 둔다", scores: { dog: 0, cat: 2, bear: 2, fox: 0 } },
      { questionId: "animal-q6", content: "중재 역할을 한다", scores: { dog: 1, cat: 0, bear: 1, fox: 1 } },
    ],
    results: [
      { id: "animal-dog", type: "dog", title: "충성스러운 강아지 🐕", description: "당신은 따뜻하고 친근한 성격의 소유자! 친구들 사이에서 인기쟁이예요. 충성스럽고 사람들과 함께하는 것을 좋아합니다." },
      { id: "animal-cat", type: "cat", title: "독립적인 고양이 🐱", description: "혼자만의 시간을 소중히 여기는 당신! 독립적이고 자기만의 세계가 확실해요. 겉으로는 쿨해 보이지만 속은 따뜻한 츤데레 매력!" },
      { id: "animal-bear", type: "bear", title: "느긋한 곰 🐻", description: "여유로움 그 자체인 당신! 급할 것 없이 자기만의 페이스를 유지해요. 포근하고 편안한 분위기로 주변을 편하게 해줍니다." },
      { id: "animal-fox", type: "fox", title: "영리한 여우 🦊", description: "눈치 빠르고 센스 있는 당신! 상황 판단이 빠르고 어디서든 잘 적응해요. 호기심이 많고 새로운 것에 도전하는 걸 좋아합니다." },
    ],
  },
  {
    test: {
      id: "tf-test-001",
      slug: "thinking-feeling",
      title: "T/F 성향 테스트",
      description: "당신은 논리적인 T? 감성적인 F? MBTI보다 정확한 T/F 판별기!",
    },
    questions: [
      { id: "tf-q1", order: 1, content: "친구가 고민 상담을 해올 때 나는?" },
      { id: "tf-q2", order: 2, content: "영화를 볼 때 주로?" },
      { id: "tf-q3", order: 3, content: "누군가 울고 있을 때?" },
      { id: "tf-q4", order: 4, content: "결정을 내릴 때 가장 중요한 건?" },
      { id: "tf-q5", order: 5, content: "칭찬을 받으면?" },
      { id: "tf-q6", order: 6, content: "친구가 이별했다고 연락이 왔을 때?" },
      { id: "tf-q7", order: 7, content: "토론할 때 나는?" },
      { id: "tf-q8", order: 8, content: "선물을 고를 때?" },
    ],
    options: [
      { questionId: "tf-q1", content: "해결책을 찾아서 조언해준다", scores: { t: 2, f: 0 } },
      { questionId: "tf-q1", content: "일단 공감하고 들어준다", scores: { t: 0, f: 2 } },
      { questionId: "tf-q1", content: "상황에 따라 다르다", scores: { t: 1, f: 1 } },
      { questionId: "tf-q2", content: "스토리 허점이나 논리를 분석한다", scores: { t: 2, f: 0 } },
      { questionId: "tf-q2", content: "감정이입해서 같이 운다", scores: { t: 0, f: 2 } },
      { questionId: "tf-q2", content: "그냥 재밌게 본다", scores: { t: 1, f: 1 } },
      { questionId: "tf-q3", content: "왜 우는지 이유가 궁금하다", scores: { t: 2, f: 0 } },
      { questionId: "tf-q3", content: "같이 슬퍼지고 위로하고 싶다", scores: { t: 0, f: 2 } },
      { questionId: "tf-q3", content: "어떻게 해야 할지 모르겠다", scores: { t: 1, f: 1 } },
      { questionId: "tf-q4", content: "객관적인 사실과 논리", scores: { t: 2, f: 0 } },
      { questionId: "tf-q4", content: "관계자들의 감정과 분위기", scores: { t: 0, f: 2 } },
      { questionId: "tf-q4", content: "둘 다 고려한다", scores: { t: 1, f: 1 } },
      { questionId: "tf-q5", content: "구체적으로 뭘 잘했는지 분석한다", scores: { t: 2, f: 0 } },
      { questionId: "tf-q5", content: "기분이 좋아지고 더 열심히 하고 싶다", scores: { t: 0, f: 2 } },
      { questionId: "tf-q5", content: "그냥 고맙다", scores: { t: 1, f: 1 } },
      { questionId: "tf-q6", content: "왜 헤어졌는지, 잘한 결정인지 물어본다", scores: { t: 2, f: 0 } },
      { questionId: "tf-q6", content: "얼마나 힘든지 공감하고 위로한다", scores: { t: 0, f: 2 } },
      { questionId: "tf-q6", content: "만나서 술 한잔 하자고 한다", scores: { t: 1, f: 1 } },
      { questionId: "tf-q7", content: "팩트와 논리로 상대를 설득한다", scores: { t: 2, f: 0 } },
      { questionId: "tf-q7", content: "분위기가 안 좋아지면 양보한다", scores: { t: 0, f: 2 } },
      { questionId: "tf-q7", content: "토론 자체를 피한다", scores: { t: 1, f: 1 } },
      { questionId: "tf-q8", content: "실용적이고 필요한 걸 고른다", scores: { t: 2, f: 0 } },
      { questionId: "tf-q8", content: "상대방이 좋아할 만한 걸 고른다", scores: { t: 0, f: 2 } },
      { questionId: "tf-q8", content: "그냥 무난한 걸 고른다", scores: { t: 1, f: 1 } },
    ],
    results: [
      { id: "tf-t", type: "t", title: "확실한 T형 인간 🧠", description: "당신은 논리와 이성의 화신! 감정보다 사실을 중시하고, 문제 해결 능력이 뛰어나요. 가끔 '차갑다'는 소리를 듣지만 사실 효율적인 것뿐! 팩트 폭격기라는 별명이 어울립니다." },
      { id: "tf-f", type: "f", title: "확실한 F형 인간 💖", description: "당신은 공감 능력 만렙! 다른 사람의 감정을 잘 읽고, 따뜻한 위로를 건네는 타입이에요. 가끔 감정에 휩쓸리기도 하지만, 그게 바로 당신의 매력! 인간 비타민 같은 존재입니다." },
    ],
  },
  {
    test: {
      id: "love-test-001",
      slug: "love-style",
      title: "연애 스타일 테스트",
      description: "나의 연애 유형은? 밀당파? 직진파? 숨겨진 연애 스타일을 알아보세요!",
    },
    questions: [
      { id: "love-q1", order: 1, content: "마음에 드는 사람이 생기면?" },
      { id: "love-q2", order: 2, content: "연인과 싸웠을 때?" },
      { id: "love-q3", order: 3, content: "이상적인 데이트는?" },
      { id: "love-q4", order: 4, content: "연인에게 가장 중요한 건?" },
      { id: "love-q5", order: 5, content: "고백은 누가?" },
      { id: "love-q6", order: 6, content: "연락 스타일은?" },
      { id: "love-q7", order: 7, content: "질투심은?" },
    ],
    options: [
      { questionId: "love-q1", content: "바로 직진! 고백한다", scores: { passionate: 2, stable: 0, independent: 0, romantic: 1 } },
      { questionId: "love-q1", content: "천천히 친해지면서 탐색한다", scores: { passionate: 0, stable: 2, independent: 1, romantic: 1 } },
      { questionId: "love-q1", content: "상대방이 먼저 다가오길 기다린다", scores: { passionate: 0, stable: 1, independent: 2, romantic: 0 } },
      { questionId: "love-q2", content: "바로 대화로 해결하려 한다", scores: { passionate: 2, stable: 1, independent: 0, romantic: 0 } },
      { questionId: "love-q2", content: "시간을 두고 천천히 풀어간다", scores: { passionate: 0, stable: 2, independent: 1, romantic: 0 } },
      { questionId: "love-q2", content: "혼자 생각을 정리한다", scores: { passionate: 0, stable: 0, independent: 2, romantic: 1 } },
      { questionId: "love-q3", content: "액티비티! 놀이공원, 여행 등", scores: { passionate: 2, stable: 0, independent: 1, romantic: 1 } },
      { questionId: "love-q3", content: "조용한 카페에서 대화", scores: { passionate: 0, stable: 2, independent: 0, romantic: 1 } },
      { questionId: "love-q3", content: "각자 취미 후 저녁에 만남", scores: { passionate: 0, stable: 1, independent: 2, romantic: 0 } },
      { questionId: "love-q3", content: "로맨틱한 분위기의 레스토랑", scores: { passionate: 1, stable: 0, independent: 0, romantic: 2 } },
      { questionId: "love-q4", content: "강한 끌림과 설렘", scores: { passionate: 2, stable: 0, independent: 0, romantic: 1 } },
      { questionId: "love-q4", content: "신뢰와 안정감", scores: { passionate: 0, stable: 2, independent: 1, romantic: 0 } },
      { questionId: "love-q4", content: "서로의 독립성 존중", scores: { passionate: 0, stable: 0, independent: 2, romantic: 0 } },
      { questionId: "love-q4", content: "로맨틱한 표현과 이벤트", scores: { passionate: 1, stable: 0, independent: 0, romantic: 2 } },
      { questionId: "love-q5", content: "당연히 내가!", scores: { passionate: 2, stable: 0, independent: 0, romantic: 1 } },
      { questionId: "love-q5", content: "서로 자연스럽게", scores: { passionate: 0, stable: 2, independent: 1, romantic: 0 } },
      { questionId: "love-q5", content: "상대방이 해줬으면...", scores: { passionate: 0, stable: 0, independent: 1, romantic: 2 } },
      { questionId: "love-q6", content: "수시로 연락! 뭐해? 밥 먹었어?", scores: { passionate: 2, stable: 0, independent: 0, romantic: 1 } },
      { questionId: "love-q6", content: "하루 1~2번 꾸준히", scores: { passionate: 0, stable: 2, independent: 0, romantic: 1 } },
      { questionId: "love-q6", content: "필요할 때만 연락해도 OK", scores: { passionate: 0, stable: 1, independent: 2, romantic: 0 } },
      { questionId: "love-q7", content: "많이 한다, 질투는 사랑의 증표!", scores: { passionate: 2, stable: 0, independent: 0, romantic: 1 } },
      { questionId: "love-q7", content: "조금은 하지만 표현 안 함", scores: { passionate: 0, stable: 2, independent: 1, romantic: 0 } },
      { questionId: "love-q7", content: "거의 안 함, 믿으니까", scores: { passionate: 0, stable: 1, independent: 2, romantic: 0 } },
    ],
    results: [
      { id: "love-passionate", type: "passionate", title: "열정적인 직진러 🔥", description: "사랑에 빠지면 불꽃처럼 타오르는 당신! 밀당은 모르고 오직 직진만 압니다. 강한 끌림을 중시하고 적극적으로 표현해요. 가끔 상대방이 부담스러워할 수도...?" },
      { id: "love-stable", type: "stable", title: "믿음직한 안정파 🏠", description: "연애도 인생도 꾸준함이 최고! 화려한 불꽃보다 따뜻한 촛불 같은 사랑을 추구해요. 신뢰와 안정을 바탕으로 오래가는 관계를 만들어가는 타입입니다." },
      { id: "love-independent", type: "independent", title: "쿨한 독립파 🦅", description: "사랑해도 나는 나! 서로의 공간을 존중하는 성숙한 연애를 추구해요. 집착은 NO, 적당한 거리감이 관계를 건강하게 만든다고 생각합니다." },
      { id: "love-romantic", type: "romantic", title: "로맨틱 드라마파 🌹", description: "영화 같은 사랑을 꿈꾸는 로맨티스트! 기념일, 이벤트, 달달한 표현... 사랑은 표현해야 의미가 있다고 생각해요. 설렘 가득한 연애가 최고!" },
    ],
  },
  {
    test: {
      id: "burnout-test-001",
      slug: "burnout-level",
      title: "번아웃 테스트",
      description: "나의 번아웃 지수는? 요즘 지쳐있진 않나요? 솔직하게 답해보세요.",
    },
    questions: [
      { id: "burn-q1", order: 1, content: "아침에 눈 떴을 때 기분은?" },
      { id: "burn-q2", order: 2, content: "요즘 취미 생활은?" },
      { id: "burn-q3", order: 3, content: "일/공부가 끝나면?" },
      { id: "burn-q4", order: 4, content: "주말이 다가오면?" },
      { id: "burn-q5", order: 5, content: "요즘 집중력은?" },
      { id: "burn-q6", order: 6, content: "식욕은?" },
      { id: "burn-q7", order: 7, content: "수면 상태는?" },
      { id: "burn-q8", order: 8, content: "사람 만나는 것은?" },
    ],
    options: [
      { questionId: "burn-q1", content: "상쾌하다! 오늘도 화이팅", scores: { healthy: 3, tired: 0, burnout: 0, danger: 0 } },
      { questionId: "burn-q1", content: "그냥저냥... 일어나긴 해야지", scores: { healthy: 0, tired: 2, burnout: 1, danger: 0 } },
      { questionId: "burn-q1", content: "눈 뜨기 싫다... 5분만 더", scores: { healthy: 0, tired: 1, burnout: 2, danger: 1 } },
      { questionId: "burn-q1", content: "왜 또 아침이야... 출근/등교 싫어", scores: { healthy: 0, tired: 0, burnout: 1, danger: 3 } },
      { questionId: "burn-q2", content: "꾸준히 하고 있다", scores: { healthy: 3, tired: 0, burnout: 0, danger: 0 } },
      { questionId: "burn-q2", content: "가끔 시간 날 때만", scores: { healthy: 1, tired: 2, burnout: 1, danger: 0 } },
      { questionId: "burn-q2", content: "할 기력이 없다", scores: { healthy: 0, tired: 1, burnout: 2, danger: 1 } },
      { questionId: "burn-q2", content: "취미가 뭐였더라?", scores: { healthy: 0, tired: 0, burnout: 1, danger: 3 } },
      { questionId: "burn-q3", content: "에너지가 남아서 다른 것도 한다", scores: { healthy: 3, tired: 0, burnout: 0, danger: 0 } },
      { questionId: "burn-q3", content: "쉬면서 재충전한다", scores: { healthy: 1, tired: 2, burnout: 0, danger: 0 } },
      { questionId: "burn-q3", content: "녹초가 되어 아무것도 못한다", scores: { healthy: 0, tired: 1, burnout: 2, danger: 1 } },
      { questionId: "burn-q3", content: "끝나도 계속 일 생각이 난다", scores: { healthy: 0, tired: 0, burnout: 1, danger: 3 } },
      { questionId: "burn-q4", content: "설렌다! 계획이 잔뜩", scores: { healthy: 3, tired: 0, burnout: 0, danger: 0 } },
      { questionId: "burn-q4", content: "드디어 쉴 수 있다", scores: { healthy: 1, tired: 2, burnout: 0, danger: 0 } },
      { questionId: "burn-q4", content: "금방 월요일이겠지...", scores: { healthy: 0, tired: 1, burnout: 2, danger: 1 } },
      { questionId: "burn-q4", content: "주말도 별 기대 없다", scores: { healthy: 0, tired: 0, burnout: 1, danger: 3 } },
      { questionId: "burn-q5", content: "잘 집중된다", scores: { healthy: 3, tired: 0, burnout: 0, danger: 0 } },
      { questionId: "burn-q5", content: "예전보다 좀 떨어진 것 같다", scores: { healthy: 1, tired: 2, burnout: 1, danger: 0 } },
      { questionId: "burn-q5", content: "집중하기 힘들다", scores: { healthy: 0, tired: 1, burnout: 2, danger: 1 } },
      { questionId: "burn-q5", content: "머리가 안 돌아간다", scores: { healthy: 0, tired: 0, burnout: 1, danger: 3 } },
      { questionId: "burn-q6", content: "정상! 맛있게 잘 먹는다", scores: { healthy: 3, tired: 0, burnout: 0, danger: 0 } },
      { questionId: "burn-q6", content: "스트레스 받으면 폭식한다", scores: { healthy: 0, tired: 2, burnout: 1, danger: 1 } },
      { questionId: "burn-q6", content: "밥 먹기 귀찮다", scores: { healthy: 0, tired: 1, burnout: 2, danger: 1 } },
      { questionId: "burn-q6", content: "먹어도 맛을 모르겠다", scores: { healthy: 0, tired: 0, burnout: 1, danger: 3 } },
      { questionId: "burn-q7", content: "잘 잔다", scores: { healthy: 3, tired: 0, burnout: 0, danger: 0 } },
      { questionId: "burn-q7", content: "가끔 뒤척인다", scores: { healthy: 1, tired: 2, burnout: 1, danger: 0 } },
      { questionId: "burn-q7", content: "잠들기 힘들다", scores: { healthy: 0, tired: 1, burnout: 2, danger: 1 } },
      { questionId: "burn-q7", content: "수면제 없이 못 잔다 / 계속 피곤하다", scores: { healthy: 0, tired: 0, burnout: 1, danger: 3 } },
      { questionId: "burn-q8", content: "좋다! 에너지를 받는다", scores: { healthy: 3, tired: 0, burnout: 0, danger: 0 } },
      { questionId: "burn-q8", content: "좋은데 피곤하다", scores: { healthy: 1, tired: 2, burnout: 1, danger: 0 } },
      { questionId: "burn-q8", content: "귀찮다... 약속 피하고 싶다", scores: { healthy: 0, tired: 1, burnout: 2, danger: 1 } },
      { questionId: "burn-q8", content: "아무도 만나고 싶지 않다", scores: { healthy: 0, tired: 0, burnout: 1, danger: 3 } },
    ],
    results: [
      { id: "burn-healthy", type: "healthy", title: "건강한 상태 💚", description: "축하해요! 당신은 현재 아주 건강한 에너지 상태를 유지하고 있어요. 일과 삶의 균형이 잘 잡혀있습니다. 지금처럼 자기 관리 잘 해주세요!" },
      { id: "burn-tired", type: "tired", title: "피로 누적 중 🟡", description: "조금 지쳐있는 상태네요. 아직 번아웃은 아니지만, 충분한 휴식이 필요해요. 주말에는 푹 쉬고, 가끔은 나를 위한 시간을 만들어보세요." },
      { id: "burn-burnout", type: "burnout", title: "번아웃 주의 🟠", description: "번아웃 초기 단계예요! 몸과 마음이 경고 신호를 보내고 있어요. 업무량을 조절하고, 스트레스 해소법을 찾아보세요. 무리하면 안 돼요!" },
      { id: "burn-danger", type: "danger", title: "심각한 번아웃 🔴", description: "많이 지쳐있네요... 혼자 해결하려 하지 마시고, 주변에 도움을 요청하세요. 필요하다면 전문가 상담도 고려해보세요. 당신의 건강이 가장 중요해요! 💙" },
    ],
  },
  {
    test: {
      id: "color-test-001",
      slug: "my-color",
      title: "나의 색깔 테스트",
      description: "당신의 영혼은 어떤 색깔? 퍼스널컬러가 아닌, 진짜 당신의 색을 찾아보세요!",
    },
    questions: [
      { id: "color-q1", order: 1, content: "가장 편안한 시간대는?" },
      { id: "color-q2", order: 2, content: "이상적인 휴가지는?" },
      { id: "color-q3", order: 3, content: "친구들 사이에서 나는?" },
      { id: "color-q4", order: 4, content: "스트레스 받을 때?" },
      { id: "color-q5", order: 5, content: "삶에서 가장 중요한 가치는?" },
      { id: "color-q6", order: 6, content: "나를 동물에 비유하면?" },
    ],
    options: [
      { questionId: "color-q1", content: "활기찬 아침", scores: { red: 2, blue: 0, yellow: 2, green: 0, purple: 0 } },
      { questionId: "color-q1", content: "평화로운 오후", scores: { red: 0, blue: 1, yellow: 1, green: 2, purple: 0 } },
      { questionId: "color-q1", content: "고요한 밤", scores: { red: 0, blue: 2, yellow: 0, green: 0, purple: 2 } },
      { questionId: "color-q2", content: "활동적인 도시 여행", scores: { red: 2, blue: 0, yellow: 2, green: 0, purple: 0 } },
      { questionId: "color-q2", content: "한적한 바닷가", scores: { red: 0, blue: 2, yellow: 0, green: 1, purple: 1 } },
      { questionId: "color-q2", content: "초록 가득한 산속", scores: { red: 0, blue: 0, yellow: 0, green: 2, purple: 1 } },
      { questionId: "color-q2", content: "예술과 문화의 도시", scores: { red: 1, blue: 1, yellow: 1, green: 0, purple: 2 } },
      { questionId: "color-q3", content: "분위기 메이커, 에너자이저", scores: { red: 2, blue: 0, yellow: 2, green: 0, purple: 0 } },
      { questionId: "color-q3", content: "조용한 경청자", scores: { red: 0, blue: 2, yellow: 0, green: 1, purple: 1 } },
      { questionId: "color-q3", content: "중재자, 평화주의자", scores: { red: 0, blue: 1, yellow: 0, green: 2, purple: 0 } },
      { questionId: "color-q3", content: "독특한 아이디어 제공자", scores: { red: 1, blue: 0, yellow: 1, green: 0, purple: 2 } },
      { questionId: "color-q4", content: "운동이나 활동으로 에너지 발산", scores: { red: 2, blue: 0, yellow: 1, green: 1, purple: 0 } },
      { questionId: "color-q4", content: "혼자만의 시간으로 충전", scores: { red: 0, blue: 2, yellow: 0, green: 1, purple: 1 } },
      { questionId: "color-q4", content: "자연 속에서 힐링", scores: { red: 0, blue: 1, yellow: 0, green: 2, purple: 0 } },
      { questionId: "color-q4", content: "음악이나 예술로 승화", scores: { red: 0, blue: 1, yellow: 0, green: 0, purple: 2 } },
      { questionId: "color-q5", content: "열정과 도전", scores: { red: 2, blue: 0, yellow: 1, green: 0, purple: 1 } },
      { questionId: "color-q5", content: "안정과 평화", scores: { red: 0, blue: 2, yellow: 0, green: 2, purple: 0 } },
      { questionId: "color-q5", content: "즐거움과 행복", scores: { red: 1, blue: 0, yellow: 2, green: 1, purple: 0 } },
      { questionId: "color-q5", content: "창의성과 개성", scores: { red: 1, blue: 0, yellow: 1, green: 0, purple: 2 } },
      { questionId: "color-q6", content: "사자 - 당당하고 리더십 있는", scores: { red: 2, blue: 0, yellow: 1, green: 0, purple: 0 } },
      { questionId: "color-q6", content: "돌고래 - 영리하고 친근한", scores: { red: 0, blue: 2, yellow: 1, green: 0, purple: 0 } },
      { questionId: "color-q6", content: "나무늘보 - 여유롭고 평화로운", scores: { red: 0, blue: 0, yellow: 0, green: 2, purple: 1 } },
      { questionId: "color-q6", content: "올빼미 - 신비롭고 지적인", scores: { red: 0, blue: 1, yellow: 0, green: 0, purple: 2 } },
    ],
    results: [
      { id: "color-red", type: "red", title: "열정의 레드 ❤️", description: "당신은 뜨거운 열정의 소유자! 도전을 두려워하지 않고, 강한 에너지로 주변을 이끌어요. 리더십이 뛰어나고 목표를 향해 돌진하는 타입입니다." },
      { id: "color-blue", type: "blue", title: "차분한 블루 💙", description: "깊은 바다처럼 고요하고 지혜로운 당신! 감정의 깊이가 있고, 신뢰할 수 있는 사람이에요. 차분하게 상황을 분석하고 현명한 결정을 내립니다." },
      { id: "color-yellow", type: "yellow", title: "밝은 옐로우 💛", description: "태양처럼 밝고 따뜻한 당신! 긍정 에너지가 넘치고 주변 사람들을 행복하게 만들어요. 유머 감각이 뛰어나고 분위기를 밝게 만드는 비타민 같은 존재!" },
      { id: "color-green", type: "green", title: "평화로운 그린 💚", description: "자연처럼 편안하고 치유하는 힘을 가진 당신! 균형과 조화를 중시하고, 사람들에게 안정감을 줘요. 갈등을 싫어하고 평화로운 관계를 추구합니다." },
      { id: "color-purple", type: "purple", title: "신비로운 퍼플 💜", description: "독특하고 창의적인 영혼의 소유자! 예술적 감각이 뛰어나고, 남들과 다른 시각으로 세상을 바라봐요. 신비로운 매력으로 사람들을 끌어당깁니다." },
    ],
  },
  {
    test: {
      id: "pastlife-test-001",
      slug: "past-life",
      title: "전생 테스트",
      description: "전생에 당신은 누구였을까? 운명의 실타래를 따라 과거로 떠나보세요!",
    },
    questions: [
      { id: "past-q1", order: 1, content: "이유 없이 끌리는 시대는?" },
      { id: "past-q2", order: 2, content: "반복되는 꿈이 있다면?" },
      { id: "past-q3", order: 3, content: "처음 가는 곳인데 익숙한 느낌이 드는 장소는?" },
      { id: "past-q4", order: 4, content: "이유 없이 두려운 것은?" },
      { id: "past-q5", order: 5, content: "특별한 재능이 있다면?" },
      { id: "past-q6", order: 6, content: "삶의 사명이 있다면?" },
    ],
    options: [
      { questionId: "past-q1", content: "고대 문명 (이집트, 그리스 등)", scores: { royal: 2, warrior: 0, artist: 1, healer: 0, scholar: 2 } },
      { questionId: "past-q1", content: "중세 유럽", scores: { royal: 2, warrior: 2, artist: 0, healer: 0, scholar: 1 } },
      { questionId: "past-q1", content: "동양의 옛 왕조", scores: { royal: 1, warrior: 1, artist: 1, healer: 1, scholar: 2 } },
      { questionId: "past-q1", content: "근대 (빅토리아, 르네상스 등)", scores: { royal: 1, warrior: 0, artist: 2, healer: 0, scholar: 1 } },
      { questionId: "past-q2", content: "높은 곳에서 떨어지는 꿈", scores: { royal: 2, warrior: 0, artist: 0, healer: 0, scholar: 1 } },
      { questionId: "past-q2", content: "전쟁이나 싸움", scores: { royal: 0, warrior: 3, artist: 0, healer: 0, scholar: 0 } },
      { questionId: "past-q2", content: "물에 빠지는 꿈", scores: { royal: 0, warrior: 0, artist: 1, healer: 2, scholar: 0 } },
      { questionId: "past-q2", content: "낯선 곳을 헤매는 꿈", scores: { royal: 0, warrior: 1, artist: 1, healer: 1, scholar: 2 } },
      { questionId: "past-q3", content: "웅장한 성이나 궁전", scores: { royal: 3, warrior: 1, artist: 0, healer: 0, scholar: 0 } },
      { questionId: "past-q3", content: "오래된 전쟁터나 요새", scores: { royal: 0, warrior: 3, artist: 0, healer: 0, scholar: 0 } },
      { questionId: "past-q3", content: "고즈넉한 사찰이나 성당", scores: { royal: 0, warrior: 0, artist: 1, healer: 2, scholar: 1 } },
      { questionId: "past-q3", content: "오래된 도서관이나 서재", scores: { royal: 0, warrior: 0, artist: 1, healer: 0, scholar: 3 } },
      { questionId: "past-q4", content: "높은 곳", scores: { royal: 2, warrior: 0, artist: 0, healer: 1, scholar: 0 } },
      { questionId: "past-q4", content: "칼이나 날카로운 것", scores: { royal: 0, warrior: 2, artist: 0, healer: 1, scholar: 0 } },
      { questionId: "past-q4", content: "불", scores: { royal: 1, warrior: 0, artist: 1, healer: 0, scholar: 2 } },
      { questionId: "past-q4", content: "어둠이나 좁은 공간", scores: { royal: 0, warrior: 1, artist: 1, healer: 2, scholar: 0 } },
      { questionId: "past-q5", content: "사람들을 이끄는 리더십", scores: { royal: 3, warrior: 1, artist: 0, healer: 0, scholar: 0 } },
      { questionId: "past-q5", content: "위기 상황에서의 판단력", scores: { royal: 1, warrior: 3, artist: 0, healer: 0, scholar: 0 } },
      { questionId: "past-q5", content: "예술적 감각", scores: { royal: 0, warrior: 0, artist: 3, healer: 0, scholar: 1 } },
      { questionId: "past-q5", content: "사람의 마음을 치유하는 능력", scores: { royal: 0, warrior: 0, artist: 0, healer: 3, scholar: 0 } },
      { questionId: "past-q6", content: "세상을 바꾸고 이끄는 것", scores: { royal: 3, warrior: 1, artist: 0, healer: 0, scholar: 0 } },
      { questionId: "past-q6", content: "약자를 보호하는 것", scores: { royal: 0, warrior: 3, artist: 0, healer: 1, scholar: 0 } },
      { questionId: "past-q6", content: "아름다움을 창조하는 것", scores: { royal: 0, warrior: 0, artist: 3, healer: 0, scholar: 1 } },
      { questionId: "past-q6", content: "지식을 전하고 가르치는 것", scores: { royal: 0, warrior: 0, artist: 0, healer: 1, scholar: 3 } },
    ],
    results: [
      { id: "past-royal", type: "royal", title: "왕족/귀족 👑", description: "전생에 당신은 높은 신분의 왕족이나 귀족이었어요! 타고난 리더십과 품위, 그리고 책임감... 사람들 위에 서서 이끌었던 기억이 DNA에 새겨져 있네요." },
      { id: "past-warrior", type: "warrior", title: "전사/기사 ⚔️", description: "전생에 당신은 용맹한 전사였어요! 정의를 위해 싸우고, 약자를 보호했던 기억... 지금도 불의를 보면 참지 못하고, 용기 있게 행동하는 건 그때의 습관이에요." },
      { id: "past-artist", type: "artist", title: "예술가 🎨", description: "전생에 당신은 아름다움을 창조하던 예술가였어요! 음악, 그림, 조각... 어떤 형태로든 예술혼을 불태웠죠. 지금도 감각이 뛰어나고 창의적인 건 그때의 재능!" },
      { id: "past-healer", type: "healer", title: "치유자/사제 🙏", description: "전생에 당신은 사람들의 몸과 마음을 치유하던 존재였어요! 의사, 사제, 무녀... 신비로운 능력으로 아픔을 달래주었죠. 지금도 공감 능력이 뛰어난 이유예요." },
      { id: "past-scholar", type: "scholar", title: "학자/현자 📚", description: "전생에 당신은 지식을 탐구하던 학자였어요! 진리를 찾아 헤매고, 책 속에 파묻혀 살았죠. 지금도 배움에 대한 갈증과 지적 호기심이 넘치는 건 그때의 습관!" },
    ],
  },
  {
    test: {
      id: "home-test-001",
      slug: "homebody-level",
      title: "집순이/집돌이 레벨 테스트",
      description: "당신의 집순이/집돌이 레벨은? 진정한 홈바디인지 알아보세요!",
    },
    questions: [
      { id: "home-q1", order: 1, content: "금요일 저녁, 친구가 갑자기 술 마시자고 하면?" },
      { id: "home-q2", order: 2, content: "택배가 도착했을 때 가장 행복한 순간은?" },
      { id: "home-q3", order: 3, content: "이상적인 주말 계획은?" },
      { id: "home-q4", order: 4, content: "집에 있을 때 주로 하는 것은?" },
      { id: "home-q5", order: 5, content: "외출할 때 기분은?" },
      { id: "home-q6", order: 6, content: "배달 앱 사용 빈도는?" },
    ],
    options: [
      { questionId: "home-q1", content: "바로 나간다! 놀아야지", scores: { outsider: 3, balanced: 1, homebody: 0, ultimate: 0 } },
      { questionId: "home-q1", content: "기분에 따라 다르다", scores: { outsider: 1, balanced: 3, homebody: 1, ultimate: 0 } },
      { questionId: "home-q1", content: "핑계 대고 거절한다", scores: { outsider: 0, balanced: 1, homebody: 3, ultimate: 1 } },
      { questionId: "home-q1", content: "읽씹한다", scores: { outsider: 0, balanced: 0, homebody: 1, ultimate: 3 } },
      { questionId: "home-q2", content: "택배 받으러 나가는 것 자체가 귀찮다", scores: { outsider: 0, balanced: 0, homebody: 2, ultimate: 3 } },
      { questionId: "home-q2", content: "문 앞에 놓아주세요 해놓기", scores: { outsider: 0, balanced: 1, homebody: 3, ultimate: 2 } },
      { questionId: "home-q2", content: "택배 기사님과 대면하기", scores: { outsider: 2, balanced: 3, homebody: 0, ultimate: 0 } },
      { questionId: "home-q2", content: "직접 픽업하러 가기", scores: { outsider: 3, balanced: 1, homebody: 0, ultimate: 0 } },
      { questionId: "home-q3", content: "친구들과 맛집 투어", scores: { outsider: 3, balanced: 1, homebody: 0, ultimate: 0 } },
      { questionId: "home-q3", content: "가까운 카페에서 책 읽기", scores: { outsider: 1, balanced: 3, homebody: 1, ultimate: 0 } },
      { questionId: "home-q3", content: "집에서 넷플릭스 정주행", scores: { outsider: 0, balanced: 1, homebody: 3, ultimate: 2 } },
      { questionId: "home-q3", content: "침대에서 뒹굴뒹굴", scores: { outsider: 0, balanced: 0, homebody: 2, ultimate: 3 } },
      { questionId: "home-q4", content: "유튜브/넷플릭스 시청", scores: { outsider: 0, balanced: 2, homebody: 3, ultimate: 2 } },
      { questionId: "home-q4", content: "게임하기", scores: { outsider: 0, balanced: 1, homebody: 2, ultimate: 3 } },
      { questionId: "home-q4", content: "요리/베이킹", scores: { outsider: 1, balanced: 3, homebody: 2, ultimate: 0 } },
      { questionId: "home-q4", content: "그냥 누워있기", scores: { outsider: 0, balanced: 0, homebody: 1, ultimate: 3 } },
      { questionId: "home-q5", content: "설렌다! 세상 구경하자", scores: { outsider: 3, balanced: 2, homebody: 0, ultimate: 0 } },
      { questionId: "home-q5", content: "그럭저럭 괜찮다", scores: { outsider: 1, balanced: 3, homebody: 1, ultimate: 0 } },
      { questionId: "home-q5", content: "빨리 집에 가고 싶다", scores: { outsider: 0, balanced: 1, homebody: 3, ultimate: 2 } },
      { questionId: "home-q5", content: "나가기 전부터 피곤하다", scores: { outsider: 0, balanced: 0, homebody: 1, ultimate: 3 } },
      { questionId: "home-q6", content: "거의 안 시킨다, 직접 나가서 먹는다", scores: { outsider: 3, balanced: 1, homebody: 0, ultimate: 0 } },
      { questionId: "home-q6", content: "주 1-2회 정도", scores: { outsider: 1, balanced: 3, homebody: 1, ultimate: 0 } },
      { questionId: "home-q6", content: "주 3-4회", scores: { outsider: 0, balanced: 1, homebody: 3, ultimate: 1 } },
      { questionId: "home-q6", content: "거의 매일... 배달 맛집 다 꿰고 있다", scores: { outsider: 0, balanced: 0, homebody: 1, ultimate: 3 } },
    ],
    results: [
      { id: "home-outsider", type: "outsider", title: "활동적인 아싸이더 🏃", description: "집보다 밖이 좋은 당신! 집에 있으면 몸이 근질근질해요. 항상 밖에서 친구들 만나고, 새로운 경험 하는 걸 좋아하는 에너자이저!" },
      { id: "home-balanced", type: "balanced", title: "균형 잡힌 밸런서 ⚖️", description: "집도 좋고 밖도 좋은 당신! 때에 따라 나갈 땐 나가고, 쉴 땐 쉬는 균형 잡힌 라이프를 즐기고 있어요. 가장 건강한 유형!" },
      { id: "home-homebody", type: "homebody", title: "집순이/집돌이 🏠", description: "집이 제일 좋은 당신! 밖에 나가는 것보다 집에서 혼자만의 시간을 보내는 게 행복해요. 침대가 친구, 이불이 연인!" },
      { id: "home-ultimate", type: "ultimate", title: "궁극의 은둔형 외톨이 🛋️", description: "집 밖은 위험해! 진정한 홈마스터인 당신. 배달앱과 OTT가 있으면 영원히 안 나가도 될 것 같아요. 방구석이 우주의 중심!" },
    ],
  },
  {
    test: {
      id: "mz-test-001",
      slug: "mz-generation",
      title: "MZ세대력 테스트",
      description: "나는 얼마나 MZ할까? 요즘 트렌드를 얼마나 알고 있는지 테스트!",
    },
    questions: [
      { id: "mz-q1", order: 1, content: "'점메추' 가 무슨 뜻인지 아시나요?" },
      { id: "mz-q2", order: 2, content: "SNS 사용 스타일은?" },
      { id: "mz-q3", order: 3, content: "회사에서 상사가 주말에 카톡 보내면?" },
      { id: "mz-q4", order: 4, content: "'갓생'을 살고 있나요?" },
      { id: "mz-q5", order: 5, content: "소비 스타일은?" },
      { id: "mz-q6", order: 6, content: "'오히려 좋아'를 실제로 사용하시나요?" },
    ],
    options: [
      { questionId: "mz-q1", content: "점심 메뉴 추천!", scores: { mzpro: 3, mz: 2, boomer: 0, ancient: 0 } },
      { questionId: "mz-q1", content: "들어본 것 같은데...", scores: { mzpro: 0, mz: 2, boomer: 2, ancient: 0 } },
      { questionId: "mz-q1", content: "처음 듣는다", scores: { mzpro: 0, mz: 0, boomer: 2, ancient: 3 } },
      { questionId: "mz-q2", content: "인스타 스토리 하루에 여러 번 올림", scores: { mzpro: 3, mz: 2, boomer: 0, ancient: 0 } },
      { questionId: "mz-q2", content: "가끔 피드에 사진 올림", scores: { mzpro: 1, mz: 3, boomer: 1, ancient: 0 } },
      { questionId: "mz-q2", content: "보기만 함, 올리는 건 귀찮", scores: { mzpro: 0, mz: 1, boomer: 3, ancient: 1 } },
      { questionId: "mz-q2", content: "SNS가 뭔가요?", scores: { mzpro: 0, mz: 0, boomer: 1, ancient: 3 } },
      { questionId: "mz-q3", content: "읽씹하고 월요일에 본다", scores: { mzpro: 3, mz: 2, boomer: 0, ancient: 0 } },
      { questionId: "mz-q3", content: "일단 읽고 급한 것만 답장", scores: { mzpro: 1, mz: 3, boomer: 1, ancient: 0 } },
      { questionId: "mz-q3", content: "바로 답장한다", scores: { mzpro: 0, mz: 0, boomer: 3, ancient: 2 } },
      { questionId: "mz-q4", content: "미라클 모닝, 운동, 자기계발 중!", scores: { mzpro: 3, mz: 2, boomer: 0, ancient: 0 } },
      { questionId: "mz-q4", content: "시도는 해봤는데...", scores: { mzpro: 1, mz: 3, boomer: 1, ancient: 0 } },
      { questionId: "mz-q4", content: "갓생이 뭔가요?", scores: { mzpro: 0, mz: 0, boomer: 2, ancient: 3 } },
      { questionId: "mz-q5", content: "YOLO! 현재를 즐긴다", scores: { mzpro: 3, mz: 2, boomer: 0, ancient: 0 } },
      { questionId: "mz-q5", content: "플렉스 할 땐 하고 아낄 땐 아낀다", scores: { mzpro: 2, mz: 3, boomer: 1, ancient: 0 } },
      { questionId: "mz-q5", content: "저축이 최고", scores: { mzpro: 0, mz: 0, boomer: 3, ancient: 2 } },
      { questionId: "mz-q6", content: "입에 달고 산다", scores: { mzpro: 3, mz: 2, boomer: 0, ancient: 0 } },
      { questionId: "mz-q6", content: "가끔 쓴다", scores: { mzpro: 1, mz: 3, boomer: 1, ancient: 0 } },
      { questionId: "mz-q6", content: "그게 뭔 소린지 모르겠다", scores: { mzpro: 0, mz: 0, boomer: 2, ancient: 3 } },
    ],
    results: [
      { id: "mz-mzpro", type: "mzpro", title: "MZ 프로 🔥", description: "트렌드의 최전선에 있는 당신! 신조어는 기본, 밈도 척척! SNS 감각도 뛰어나고 요즘 문화를 완벽하게 즐기고 있어요. 진정한 MZ 네이티브!" },
      { id: "mz-mz", type: "mz", title: "평범한 MZ 👍", description: "MZ세대 평균! 트렌드를 어느 정도 따라가면서도 자기만의 스타일을 유지하고 있어요. 적당히 힙하고 적당히 편안한 균형 잡힌 MZ!" },
      { id: "mz-boomer", type: "boomer", title: "마음은 MZ, 몸은 부머 👴", description: "트렌드에 관심은 있는데 따라가기 버거운 당신. 신조어가 나오면 몰래 검색하고, 요즘 것들이 낯설 때도 있어요. 그래도 괜찮아요, 세대는 숫자일 뿐!" },
      { id: "mz-ancient", type: "ancient", title: "타임머신 탑승자 🕰️", description: "MZ세대와는 거리가 먼 당신... 하지만 괜찮아요! 트렌드를 몰라도 인생을 즐기는 방법은 많으니까요. 오히려 힙할 수도?" },
    ],
  },
  {
    test: {
      id: "money-test-001",
      slug: "money-type",
      title: "금전 감각 테스트",
      description: "당신의 소비 유형은? 플렉서? 짠돌이? 돈 관리 스타일을 알아보세요!",
    },
    questions: [
      { id: "money-q1", order: 1, content: "월급날, 가장 먼저 하는 것은?" },
      { id: "money-q2", order: 2, content: "친구들과 밥 먹을 때 계산은?" },
      { id: "money-q3", order: 3, content: "세일 기간에 마음에 드는 옷을 발견하면?" },
      { id: "money-q4", order: 4, content: "적금/투자 상황은?" },
      { id: "money-q5", order: 5, content: "배달 음식 시킬 때?" },
      { id: "money-q6", order: 6, content: "로또 1등에 당첨되면?" },
    ],
    options: [
      { questionId: "money-q1", content: "바로 쇼핑! 나를 위한 선물", scores: { flex: 3, balanced: 0, saver: 0, investor: 0 } },
      { questionId: "money-q1", content: "일단 저축하고 남은 돈으로 생활", scores: { flex: 0, balanced: 1, saver: 3, investor: 1 } },
      { questionId: "money-q1", content: "투자 계좌로 자동이체", scores: { flex: 0, balanced: 1, saver: 1, investor: 3 } },
      { questionId: "money-q1", content: "예산 짜고 계획적으로 사용", scores: { flex: 0, balanced: 3, saver: 2, investor: 1 } },
      { questionId: "money-q2", content: "내가 쏜다! 플렉스!", scores: { flex: 3, balanced: 1, saver: 0, investor: 0 } },
      { questionId: "money-q2", content: "N빵이 공평하다", scores: { flex: 0, balanced: 3, saver: 2, investor: 1 } },
      { questionId: "money-q2", content: "더치페이 앱으로 정확하게", scores: { flex: 0, balanced: 2, saver: 3, investor: 1 } },
      { questionId: "money-q3", content: "고민 없이 바로 산다", scores: { flex: 3, balanced: 0, saver: 0, investor: 0 } },
      { questionId: "money-q3", content: "필요한지 생각해보고 결정", scores: { flex: 0, balanced: 3, saver: 1, investor: 1 } },
      { questionId: "money-q3", content: "최저가 검색 후 더 싼 곳에서 구매", scores: { flex: 0, balanced: 1, saver: 3, investor: 0 } },
      { questionId: "money-q3", content: "세일이어도 안 산다, 계획에 없었으니까", scores: { flex: 0, balanced: 1, saver: 2, investor: 3 } },
      { questionId: "money-q4", content: "적금? 투자? 그런 거 안 해요", scores: { flex: 3, balanced: 0, saver: 0, investor: 0 } },
      { questionId: "money-q4", content: "적금 하나 정도는 있다", scores: { flex: 0, balanced: 2, saver: 3, investor: 0 } },
      { questionId: "money-q4", content: "주식, ETF, 코인 등 투자 중", scores: { flex: 1, balanced: 1, saver: 0, investor: 3 } },
      { questionId: "money-q4", content: "적금도 하고 투자도 한다", scores: { flex: 0, balanced: 3, saver: 2, investor: 2 } },
      { questionId: "money-q5", content: "배달비? 신경 안 쓴다", scores: { flex: 3, balanced: 1, saver: 0, investor: 0 } },
      { questionId: "money-q5", content: "배달비 포함해서 가성비 계산", scores: { flex: 0, balanced: 3, saver: 2, investor: 1 } },
      { questionId: "money-q5", content: "배달비 아까워서 직접 포장", scores: { flex: 0, balanced: 1, saver: 3, investor: 1 } },
      { questionId: "money-q6", content: "일단 명품부터!", scores: { flex: 3, balanced: 0, saver: 0, investor: 0 } },
      { questionId: "money-q6", content: "반은 저축, 반은 사용", scores: { flex: 0, balanced: 3, saver: 2, investor: 1 } },
      { questionId: "money-q6", content: "전액 예금, 이자로 생활", scores: { flex: 0, balanced: 1, saver: 3, investor: 1 } },
      { questionId: "money-q6", content: "부동산이나 주식에 투자", scores: { flex: 1, balanced: 1, saver: 0, investor: 3 } },
    ],
    results: [
      { id: "money-flex", type: "flex", title: "플렉서 💸", description: "돈은 쓰라고 있는 것! 인생은 한 번뿐이니까 현재를 즐기는 당신. 통장 잔고보다 지금의 행복이 중요해요. 가끔은 미래도 생각해보는 건 어떨까요?" },
      { id: "money-balanced", type: "balanced", title: "균형 잡힌 소비러 ⚖️", description: "쓸 때 쓰고 아낄 때 아끼는 균형 잡힌 금전 감각의 소유자! 충동구매도 피하고, 필요한 곳에는 투자하는 현명한 소비 습관을 가지고 있어요." },
      { id: "money-saver", type: "saver", title: "저축왕 짠돌이 💰", description: "티끌 모아 태산! 저축의 기쁨을 아는 당신. 불필요한 소비는 NO, 알뜰살뜰 모으는 재미가 있어요. 가끔은 나를 위한 소비도 해보세요!" },
      { id: "money-investor", type: "investor", title: "투자 고수 📈", description: "돈이 돈을 벌게 하는 당신! 재테크에 관심이 많고, 자산을 불리는 방법을 잘 알고 있어요. 장기적인 관점에서 현명한 금융 전략을 세우는 타입!" },
    ],
  },
  {
    test: {
      id: "work-test-001",
      slug: "work-style",
      title: "직장인 유형 테스트",
      description: "회사에서 당신은 어떤 타입? 나의 직장인 캐릭터를 알아보세요!",
    },
    questions: [
      { id: "work-q1", order: 1, content: "월요일 아침 기분은?" },
      { id: "work-q2", order: 2, content: "점심시간에 주로?" },
      { id: "work-q3", order: 3, content: "야근 요청이 들어오면?" },
      { id: "work-q4", order: 4, content: "회의 시간에 나는?" },
      { id: "work-q5", order: 5, content: "동료와 갈등이 생기면?" },
      { id: "work-q6", order: 6, content: "퇴근 시간이 되면?" },
    ],
    options: [
      { questionId: "work-q1", content: "오늘도 화이팅! 의욕 충만", scores: { passionate: 3, steady: 1, quiet: 0, rebel: 0 } },
      { questionId: "work-q1", content: "그냥저냥, 일상이니까", scores: { passionate: 0, steady: 3, quiet: 1, rebel: 0 } },
      { questionId: "work-q1", content: "벌써 금요일이 기다려진다", scores: { passionate: 0, steady: 1, quiet: 2, rebel: 2 } },
      { questionId: "work-q1", content: "출근하기 싫다...", scores: { passionate: 0, steady: 0, quiet: 2, rebel: 3 } },
      { questionId: "work-q2", content: "동료들과 맛집 탐방!", scores: { passionate: 2, steady: 2, quiet: 0, rebel: 1 } },
      { questionId: "work-q2", content: "간단히 먹고 산책", scores: { passionate: 1, steady: 3, quiet: 1, rebel: 0 } },
      { questionId: "work-q2", content: "혼밥하며 유튜브", scores: { passionate: 0, steady: 1, quiet: 3, rebel: 1 } },
      { questionId: "work-q2", content: "밥보다 낮잠이 중요", scores: { passionate: 0, steady: 0, quiet: 1, rebel: 3 } },
      { questionId: "work-q3", content: "오케이! 열심히 하죠", scores: { passionate: 3, steady: 1, quiet: 0, rebel: 0 } },
      { questionId: "work-q3", content: "이유를 듣고 판단한다", scores: { passionate: 1, steady: 3, quiet: 1, rebel: 0 } },
      { questionId: "work-q3", content: "내심 싫지만 한다", scores: { passionate: 0, steady: 1, quiet: 3, rebel: 1 } },
      { questionId: "work-q3", content: "정중하게 거절한다", scores: { passionate: 0, steady: 0, quiet: 1, rebel: 3 } },
      { questionId: "work-q4", content: "적극적으로 의견 제시", scores: { passionate: 3, steady: 1, quiet: 0, rebel: 1 } },
      { questionId: "work-q4", content: "필요할 때만 발언", scores: { passionate: 1, steady: 3, quiet: 1, rebel: 0 } },
      { questionId: "work-q4", content: "조용히 듣고만 있다", scores: { passionate: 0, steady: 1, quiet: 3, rebel: 0 } },
      { questionId: "work-q4", content: "회의 자체가 시간 낭비라고 생각", scores: { passionate: 0, steady: 0, quiet: 1, rebel: 3 } },
      { questionId: "work-q5", content: "바로 대화로 해결하려 한다", scores: { passionate: 3, steady: 1, quiet: 0, rebel: 1 } },
      { questionId: "work-q5", content: "시간을 두고 천천히 풀어간다", scores: { passionate: 0, steady: 3, quiet: 1, rebel: 0 } },
      { questionId: "work-q5", content: "그냥 피한다, 갈등 싫어", scores: { passionate: 0, steady: 1, quiet: 3, rebel: 0 } },
      { questionId: "work-q5", content: "내 할 일만 하면 된다", scores: { passionate: 0, steady: 0, quiet: 1, rebel: 3 } },
      { questionId: "work-q6", content: "일이 남았으면 마무리하고 간다", scores: { passionate: 3, steady: 2, quiet: 0, rebel: 0 } },
      { questionId: "work-q6", content: "칼퇴! 정시 퇴근이 원칙", scores: { passionate: 0, steady: 2, quiet: 1, rebel: 2 } },
      { questionId: "work-q6", content: "눈치 보다가 슬쩍 나간다", scores: { passionate: 0, steady: 1, quiet: 3, rebel: 0 } },
      { questionId: "work-q6", content: "퇴근 시간 전부터 짐 싸놓음", scores: { passionate: 0, steady: 0, quiet: 1, rebel: 3 } },
    ],
    results: [
      { id: "work-passionate", type: "passionate", title: "열정 만수르 🔥", description: "일이 곧 삶인 당신! 회사에서 누구보다 열정적으로 일하고, 성과를 내는 것에 보람을 느껴요. 가끔은 쉬어가며 워라밸도 챙겨보세요!" },
      { id: "work-steady", type: "steady", title: "안정적인 모범생 📚", description: "묵묵히 자기 할 일 하는 믿음직한 당신! 튀지 않지만 꾸준하고 성실해요. 회사 입장에서 가장 믿음직한 타입이에요." },
      { id: "work-quiet", type: "quiet", title: "조용한 생존러 🤫", description: "눈에 띄지 않게 조용히 생존하는 당신. 불필요한 갈등은 피하고, 적당히 일하며 평화롭게 지내는 게 목표예요. 현명한 처세술의 소유자!" },
      { id: "work-rebel", type: "rebel", title: "퇴사각 재는 중 🚪", description: "회사? 그냥 돈 벌러 오는 곳! 워라밸을 최우선으로 생각하고, 언제든 떠날 준비가 되어있어요. 마음은 이미 퇴근 중... 아니, 퇴사 중?" },
    ],
  },
  {
    test: {
      id: "smart-test-001",
      slug: "smartphone-addiction",
      title: "스마트폰 중독 레벨 테스트",
      description: "혹시 나도 도파민 중독? 숏폼 없이 못 사는 당신을 위한 진단!",
    },
    questions: [
      { id: "smart-q1", order: 1, content: "아침에 일어나서 가장 먼저 하는 것은?" },
      { id: "smart-q2", order: 2, content: "화장실 갈 때 스마트폰은?" },
      { id: "smart-q3", order: 3, content: "자기 전 루틴은?" },
      { id: "smart-q4", order: 4, content: "배터리가 10% 남았다면?" },
      { id: "smart-q5", order: 5, content: "친구와 대화 중 알림이 울리면?" },
      { id: "smart-q6", order: 6, content: "스마트폰 없이 하루 보내기 가능?" },
    ],
    options: [
      { questionId: "smart-q1", content: "알람 끄고 바로 SNS 확인", scores: { heavy: 3, moderate: 1, mild: 0, clean: 0 } },
      { questionId: "smart-q1", content: "시간만 확인하고 일어남", scores: { heavy: 0, moderate: 1, mild: 2, clean: 1 } },
      { questionId: "smart-q1", content: "물 마시거나 스트레칭", scores: { heavy: 0, moderate: 0, mild: 1, clean: 3 } },
      { questionId: "smart-q1", content: "유튜브 쇼츠 무한 스크롤", scores: { heavy: 3, moderate: 1, mild: 0, clean: 0 } },
      { questionId: "smart-q2", content: "무조건 가져간다", scores: { heavy: 3, moderate: 2, mild: 1, clean: 0 } },
      { questionId: "smart-q2", content: "급할 때만 가져감", scores: { heavy: 0, moderate: 1, mild: 2, clean: 1 } },
      { questionId: "smart-q2", content: "안 가져감", scores: { heavy: 0, moderate: 0, mild: 1, clean: 3 } },
      { questionId: "smart-q3", content: "보다가 폰 떨어뜨리고 잠듦", scores: { heavy: 3, moderate: 1, mild: 0, clean: 0 } },
      { questionId: "smart-q3", content: "1시간 정도 보다가 잠", scores: { heavy: 1, moderate: 2, mild: 1, clean: 0 } },
      { questionId: "smart-q3", content: "알람만 맞추고 잠", scores: { heavy: 0, moderate: 0, mild: 1, clean: 3 } },
      { questionId: "smart-q4", content: "불안해서 바로 충전기 찾음", scores: { heavy: 3, moderate: 2, mild: 0, clean: 0 } },
      { questionId: "smart-q4", content: "아껴서 쓴다", scores: { heavy: 0, moderate: 1, mild: 2, clean: 0 } },
      { questionId: "smart-q4", content: "꺼져도 상관없다", scores: { heavy: 0, moderate: 0, mild: 1, clean: 3 } },
      { questionId: "smart-q5", content: "바로 확인한다", scores: { heavy: 3, moderate: 1, mild: 0, clean: 0 } },
      { questionId: "smart-q5", content: "슬쩍 보고 중요하면 본다", scores: { heavy: 1, moderate: 2, mild: 1, clean: 0 } },
      { questionId: "smart-q5", content: "대화에 집중한다", scores: { heavy: 0, moderate: 0, mild: 1, clean: 3 } },
      { questionId: "smart-q6", content: "절대 불가능! 금단현상 옴", scores: { heavy: 3, moderate: 0, mild: 0, clean: 0 } },
      { questionId: "smart-q6", content: "심심하겠지만 가능은 함", scores: { heavy: 0, moderate: 2, mild: 1, clean: 0 } },
      { questionId: "smart-q6", content: "오히려 좋아, 디톡스!", scores: { heavy: 0, moderate: 0, mild: 1, clean: 3 } },
    ],
    results: [
      { id: "smart-heavy", type: "heavy", title: "스마트폰과 한 몸 🤖", description: "심각한 중독! 스마트폰 없이는 1분도 견디기 힘드시군요. 도파민 디톡스가 시급합니다. 잠시 폰을 내려놓고 현실 세계를 즐겨보세요!" },
      { id: "smart-moderate", type: "moderate", title: "평범한 현대인 📱", description: "적당히 즐기는 편이지만, 가끔은 의존도가 높아질 때가 있어요. 의식적으로 사용 시간을 줄이려는 노력이 필요해요." },
      { id: "smart-mild", type: "mild", title: "건강한 사용자 👍", description: "스마트폰을 도구로 잘 활용하고 계시군요! 필요할 때만 쓰고, 현실 생활에도 충실한 균형 잡힌 타입입니다." },
      { id: "smart-clean", type: "clean", title: "디지털 청정구역 🌿", description: "스마트폰 없이도 너무 잘 사는 당신! 아날로그 감성을 즐길 줄 아는 진정한 자유인입니다. 주변에서 부러워할 수도?" },
    ],
  },
  {
    test: {
      id: "bread-test-001",
      slug: "bread-personality",
      title: "빵 성격 테스트",
      description: "겉바속촉 크루아상? 묵직한 단팥빵? 나의 성격을 빵으로 알아봐요.",
    },
    questions: [
      { id: "bread-q1", order: 1, content: "빵집에 들어갔을 때 가장 먼저 눈길이 가는 곳은?" },
      { id: "bread-q2", order: 2, content: "친구와의 약속이 취소되면?" },
      { id: "bread-q3", order: 3, content: "일을 처리하는 방식은?" },
      { id: "bread-q4", order: 4, content: "나의 매력 포인트는?" },
      { id: "bread-q5", order: 5, content: "스트레스 해소법은?" },
    ],
    options: [
      { questionId: "bread-q1", content: "화려한 케이크와 타르트", scores: { croissant: 3, redbean: 0, baguette: 0, salt: 1 } },
      { questionId: "bread-q1", content: "기본적인 식빵이나 바게트", scores: { croissant: 0, redbean: 1, baguette: 3, salt: 0 } },
      { questionId: "bread-q1", content: "달콤한 팥빵이나 크림빵", scores: { croissant: 1, redbean: 3, baguette: 0, salt: 0 } },
      { questionId: "bread-q1", content: "짭짤한 소금빵이나 피자빵", scores: { croissant: 1, redbean: 0, baguette: 1, salt: 3 } },
      { questionId: "bread-q2", content: "아싸! 집에서 쉰다", scores: { croissant: 0, redbean: 2, baguette: 1, salt: 0 } },
      { questionId: "bread-q2", content: "다른 친구에게 연락한다", scores: { croissant: 3, redbean: 0, baguette: 0, salt: 2 } },
      { questionId: "bread-q2", content: "혼자 쇼핑이나 영화", scores: { croissant: 2, redbean: 0, baguette: 1, salt: 3 } },
      { questionId: "bread-q3", content: "빠르고 효율적으로", scores: { croissant: 3, redbean: 0, baguette: 2, salt: 1 } },
      { questionId: "bread-q3", content: "꼼꼼하고 신중하게", scores: { croissant: 0, redbean: 2, baguette: 3, salt: 0 } },
      { questionId: "bread-q3", content: "융통성 있게 상황에 맞춰", scores: { croissant: 1, redbean: 3, baguette: 0, salt: 2 } },
      { questionId: "bread-q4", content: "세련되고 트렌디함", scores: { croissant: 3, redbean: 0, baguette: 0, salt: 1 } },
      { questionId: "bread-q4", content: "편안하고 친근함", scores: { croissant: 0, redbean: 3, baguette: 0, salt: 0 } },
      { questionId: "bread-q4", content: "솔직하고 담백함", scores: { croissant: 0, redbean: 0, baguette: 3, salt: 1 } },
      { questionId: "bread-q4", content: "톡톡 튀는 반전 매력", scores: { croissant: 1, redbean: 0, baguette: 0, salt: 3 } },
      { questionId: "bread-q5", content: "맛있는 거 먹기", scores: { croissant: 2, redbean: 3, baguette: 0, salt: 2 } },
      { questionId: "bread-q5", content: "쇼핑하거나 꾸미기", scores: { croissant: 3, redbean: 0, baguette: 0, salt: 1 } },
      { questionId: "bread-q5", content: "혼자 조용히 생각 정리", scores: { croissant: 0, redbean: 1, baguette: 3, salt: 0 } },
    ],
    results: [
      { id: "bread-croissant", type: "croissant", title: "화려한 크루아상 🥐", description: "겹겹이 쌓인 페이스트리처럼 다채로운 매력의 소유자! 트렌디하고 세련된 당신은 어디서나 주목받는 인싸 재질입니다." },
      { id: "bread-redbean", type: "redbean", title: "달콤한 단팥빵 🥯", description: "누구에게나 사랑받는 클래식! 따뜻하고 정이 많은 당신은 주변 사람들을 편안하게 해주는 치유의 아이콘이에요." },
      { id: "bread-baguette", type: "baguette", title: "담백한 바게트 🥖", description: "겉은 바삭하지만 속은 부드러운 당신! 겉보기엔 차가워 보일 수 있지만, 알면 알수록 진국인 볼매 스타일입니다." },
      { id: "bread-salt", type: "salt", title: "중독성 강한 소금빵 🧂", description: "짭짤하면서도 고소한 반전 매력! 평범해 보이지만 한번 빠지면 헤어 나올 수 없는 마성의 매력을 가졌어요." },
    ],
  },
  {
    test: {
      id: "travel-test-001",
      slug: "travel-style",
      title: "여행 스타일 테스트",
      description: "분 단위 계획표 J형 vs 발길 닿는 대로 P형! 환상의 여행 메이트는?",
    },
    questions: [
      { id: "travel-q1", order: 1, content: "여행 가기 전 계획은?" },
      { id: "travel-q2", order: 2, content: "짐 쌀 때 스타일은?" },
      { id: "travel-q3", order: 3, content: "여행지에서 길을 잃었다면?" },
      { id: "travel-q4", order: 4, content: "식사 메뉴 결정은?" },
      { id: "travel-q5", order: 5, content: "여행 중 돌발 상황 발생!" },
    ],
    options: [
      { questionId: "travel-q1", content: "엑셀로 분 단위 계획표 작성", scores: { planner: 3, adventurer: 0, healer: 1, photographer: 0 } },
      { questionId: "travel-q1", content: "큰 틀만 정하고 가서 결정", scores: { planner: 0, adventurer: 3, healer: 2, photographer: 1 } },
      { questionId: "travel-q1", content: "항공권, 숙소만 예약 끝", scores: { planner: 0, adventurer: 3, healer: 1, photographer: 0 } },
      { questionId: "travel-q2", content: "비상약부터 멀티탭까지 바리바리", scores: { planner: 3, adventurer: 1, healer: 0, photographer: 2 } },
      { questionId: "travel-q2", content: "최소한의 짐만 가볍게", scores: { planner: 0, adventurer: 3, healer: 2, photographer: 0 } },
      { questionId: "travel-q2", content: "옷이랑 카메라만 챙기면 됨", scores: { planner: 0, adventurer: 1, healer: 0, photographer: 3 } },
      { questionId: "travel-q3", content: "바로 지도를 켜고 위치 파악", scores: { planner: 3, adventurer: 0, healer: 0, photographer: 0 } },
      { questionId: "travel-q3", content: "이것도 추억이지! 구경하며 걷는다", scores: { planner: 0, adventurer: 3, healer: 1, photographer: 2 } },
      { questionId: "travel-q3", content: "지나가는 사람에게 물어본다", scores: { planner: 1, adventurer: 2, healer: 2, photographer: 0 } },
      { questionId: "travel-q4", content: "미리 찾아둔 맛집 리스트 방문", scores: { planner: 3, adventurer: 0, healer: 0, photographer: 1 } },
      { questionId: "travel-q4", content: "현지인이 많은 식당 들어감", scores: { planner: 0, adventurer: 3, healer: 1, photographer: 0 } },
      { questionId: "travel-q4", content: "걷다가 분위기 좋은 곳", scores: { planner: 0, adventurer: 1, healer: 2, photographer: 3 } },
      { questionId: "travel-q5", content: "당황하지만 플랜 B 가동", scores: { planner: 3, adventurer: 0, healer: 0, photographer: 0 } },
      { questionId: "travel-q5", content: "오히려 좋아! 새로운 모험 시작", scores: { planner: 0, adventurer: 3, healer: 1, photographer: 0 } },
      { questionId: "travel-q5", content: "일단 멘붕... 카페 가서 쉰다", scores: { planner: 0, adventurer: 0, healer: 3, photographer: 0 } },
    ],
    results: [
      { id: "travel-planner", type: "planner", title: "프로 계획러 📋", description: "여행은 계획대로 되어야 제맛! 완벽한 스케줄과 준비로 실패 없는 여행을 만드는 가이드 타입. 친구들이 믿고 따르는 든든한 리더입니다." },
      { id: "travel-adventurer", type: "adventurer", title: "자유로운 모험가 🎒", description: "계획은 사치! 발길 닿는 대로 떠나는 진정한 여행자. 돌발 상황도 즐길 줄 아는 긍정 마인드로 잊지 못할 추억을 만듭니다." },
      { id: "travel-healer", type: "healer", title: "힐링 추구 휴양러 🏖️", description: "여행은 쉬러 가는 거지! 좋은 숙소, 맛있는 음식, 여유로운 풍경... 바쁜 일상을 떠나 진정한 휴식을 즐기는 타입입니다." },
      { id: "travel-photographer", type: "photographer", title: "인생샷 사냥꾼 📸", description: "남는 건 사진뿐! 예쁜 장소, 힙한 카페는 필수 코스. 여행지의 모든 순간을 기록으로 남기는 감성 여행자입니다." },
    ],
  },
  {
    test: {
      id: "friend-test-001",
      slug: "friendship-style",
      title: "찐친 유형 테스트",
      description: "나는 어떤 친구일까? 팩폭 날리는 조언가? 무조건 내 편 공감러?",
    },
    questions: [
      { id: "friend-q1", order: 1, content: "친구가 우울하다고 연락하면?" },
      { id: "friend-q2", order: 2, content: "친구가 잘못된 선택을 하려 할 때?" },
      { id: "friend-q3", order: 3, content: "친구 생일 선물 준비는?" },
      { id: "friend-q4", order: 4, content: "오랜만에 만난 친구와 대화 주제는?" },
    ],
    options: [
      { questionId: "friend-q1", content: "무슨 일이야? 바로 전화/만남", scores: { loyal: 3, fun: 1, advisor: 1, listener: 2 } },
      { questionId: "friend-q1", content: "기프티콘 보내주며 위로", scores: { loyal: 1, fun: 0, advisor: 0, listener: 2 } },
      { questionId: "friend-q1", content: "재밌는 짤이나 영상 보냄", scores: { loyal: 0, fun: 3, advisor: 0, listener: 0 } },
      { questionId: "friend-q2", content: "직설적으로 팩폭 날림", scores: { loyal: 1, fun: 0, advisor: 3, listener: 0 } },
      { questionId: "friend-q2", content: "돌려서 말하며 설득함", scores: { loyal: 2, fun: 0, advisor: 2, listener: 1 } },
      { questionId: "friend-q2", content: "일단 지켜본다", scores: { loyal: 0, fun: 1, advisor: 0, listener: 3 } },
      { questionId: "friend-q3", content: "친구가 갖고 싶어 했던 것 기억해서 줌", scores: { loyal: 3, fun: 0, advisor: 1, listener: 2 } },
      { questionId: "friend-q3", content: "실용적인 현금이나 상품권", scores: { loyal: 1, fun: 1, advisor: 3, listener: 0 } },
      { questionId: "friend-q3", content: "깜짝 파티나 이벤트", scores: { loyal: 2, fun: 3, advisor: 0, listener: 0 } },
      { questionId: "friend-q4", content: "추억 팔이, 옛날 얘기", scores: { loyal: 2, fun: 1, advisor: 0, listener: 3 } },
      { questionId: "friend-q4", content: "요즘 유행하는 핫한 얘기", scores: { loyal: 0, fun: 3, advisor: 0, listener: 1 } },
      { questionId: "friend-q4", content: "진지한 인생 고민 상담", scores: { loyal: 1, fun: 0, advisor: 3, listener: 2 } },
    ],
    results: [
      { id: "friend-loyal", type: "loyal", title: "의리파 보스 😎", description: "내 사람은 내가 챙긴다! 친구를 위해서라면 물불 안 가리는 의리파. 든든한 버팀목이 되어주는 믿음직한 친구입니다." },
      { id: "friend-fun", type: "fun", title: "분위기 메이커 🥳", description: "너랑 있으면 시간 가는 줄 몰라! 항상 웃음을 주고 분위기를 띄우는 해피 바이러스. 우울할 때 찾게 되는 비타민 같은 친구!" },
      { id: "friend-advisor", type: "advisor", title: "팩폭 조언가 🤓", description: "쓴소리도 마다하지 않는 진정한 친구. 냉철한 판단력으로 현실적인 조언을 해주며 친구의 성장을 돕는 멘토 타입입니다." },
      { id: "friend-listener", type: "listener", title: "대나무 숲 🎋", description: "말하지 않아도 알아요~ 친구의 이야기를 묵묵히 들어주고 비밀을 지켜주는 포근한 친구. 같이 있는 것만으로도 위로가 되는 존재!" },
    ],
  },
  {
    test: {
      id: "mental-test-001",
      slug: "mental-age",
      title: "정신 연령 테스트",
      description: "내 얼굴 말고 내 마음! 나는 성숙한 어른일까, 천진난만한 아이일까?",
    },
    questions: [
      { id: "mental-q1", order: 1, content: "장난감 코너를 지나갈 때?" },
      { id: "mental-q2", order: 2, content: "쉬는 날 가장 하고 싶은 것?" },
      { id: "mental-q3", order: 3, content: "어려운 일이 생겼을 때?" },
      { id: "mental-q4", order: 4, content: "애니메이션 영화를 볼 때?" },
    ],
    options: [
      { questionId: "mental-q1", content: "우와! 하고 구경한다", scores: { child: 3, teen: 1, adult: 0, elder: 0 } },
      { questionId: "mental-q1", content: "요즘 애들은 뭐 갖고 노나 봄", scores: { child: 0, teen: 2, adult: 1, elder: 0 } },
      { questionId: "mental-q1", content: "관심 없다, 지나친다", scores: { child: 0, teen: 0, adult: 3, elder: 2 } },
      { questionId: "mental-q2", content: "하루 종일 게임하고 놀기", scores: { child: 3, teen: 2, adult: 0, elder: 0 } },
      { questionId: "mental-q2", content: "친구들과 시끌벅적하게 놀기", scores: { child: 2, teen: 3, adult: 1, elder: 0 } },
      { questionId: "mental-q2", content: "밀린 집안일 하거나 휴식", scores: { child: 0, teen: 0, adult: 3, elder: 2 } },
      { questionId: "mental-q2", content: "등산이나 독서", scores: { child: 0, teen: 0, adult: 1, elder: 3 } },
      { questionId: "mental-q3", content: "엄마나 친구에게 찡찡댐", scores: { child: 3, teen: 1, adult: 0, elder: 0 } },
      { questionId: "mental-q3", content: "혼자 끙끙 앓음", scores: { child: 1, teen: 3, adult: 1, elder: 0 } },
      { questionId: "mental-q3", content: "이성적으로 해결 방법 찾음", scores: { child: 0, teen: 0, adult: 3, elder: 1 } },
      { questionId: "mental-q3", content: "인생이 다 그렇지 뭐... 허허", scores: { child: 0, teen: 0, adult: 1, elder: 3 } },
      { questionId: "mental-q4", content: "주인공에게 완전 몰입해서 봄", scores: { child: 3, teen: 1, adult: 0, elder: 0 } },
      { questionId: "mental-q4", content: "유치하다고 생각함", scores: { child: 0, teen: 3, adult: 1, elder: 0 } },
      { questionId: "mental-q4", content: "동심을 느끼며 힐링함", scores: { child: 1, teen: 0, adult: 3, elder: 1 } },
      { questionId: "mental-q4", content: "교훈적인 내용을 찾음", scores: { child: 0, teen: 0, adult: 1, elder: 3 } },
    ],
    results: [
      { id: "mental-child", type: "child", title: "응애! 5세 영혼 👶", description: "순수함 그 자체! 호기심 많고 감정 표현에 솔직한 당신. 세상은 놀이터고 하루하루가 즐거워요. 때 묻지 않은 동심을 간직하고 있네요." },
      { id: "mental-teen", type: "teen", title: "질풍노도 18세 ⚡", description: "감수성 폭발! 반항기와 열정이 공존하는 사춘기 영혼. 남들의 시선을 의식하기도 하고, 폼생폼사를 추구하기도 하는 매력적인 10대 감성!" },
      { id: "mental-adult", type: "adult", title: "현실적인 30대 💼", description: "책임감 강한 어른! 이성적이고 현실적인 판단을 중요하게 생각해요. 사회생활 만렙, 웬만한 일에는 눈 하나 깜짝 안 하는 프로 사회인입니다." },
      { id: "mental-elder", type: "elder", title: "인생 2회차 80대 🍵", description: "모든 것을 통달한 현자! 작은 일에 일희일비하지 않고, 삶을 관조하는 여유가 있어요. 친구들이 상담하러 자주 오는 정신적 지주!" },
    ],
  },
];

async function seedTest(testData: TestData) {
  const { test, questions: qs, options: opts, results } = testData;

  await db.insert(tests).values({
    ...test,
    thumbnailUrl: null,
    totalParticipants: 0,
  }).onConflictDoNothing();

  for (const q of qs) {
    await db.insert(questions).values({ ...q, testId: test.id }).onConflictDoNothing();
  }

  for (let i = 0; i < opts.length; i++) {
    const opt = opts[i];
    await db.insert(options).values({
      id: `${test.id}-opt-${i}`,
      questionId: opt.questionId,
      content: opt.content,
      scores: JSON.stringify(opt.scores),
    }).onConflictDoNothing();
  }

  for (const result of results) {
    await db.insert(resultTypes).values({
      ...result,
      testId: test.id,
      imageUrl: null,
      count: 0,
    }).onConflictDoNothing();
  }

  console.log(`✅ ${test.title} seeded!`);
}

export async function seedAllTests() {
  for (const testData of allTests) {
    await seedTest(testData);
  }
  console.log("\n🎉 All tests seeded successfully!");
}
